// En Alumnos.php, dentro de public function index()
// ...
// 2. Obtén todos los registros de la tabla 'alumnos'
$data['estudiantes'] = $model->findAll(); // ¡Cambiado de 'alumnos' a 'estudiantes'!
// ...